### PR TITLE
v1: Fix CI and add Fedora target

### PR DESCRIPTION
**Pull request by Conan-Kudo**
This fixes the GitHub Actions configuration so that Alpine CI works and adds a Fedora Rawhide CI target to ensure a glibc target is included.

### CODE REVIEW

**Review by serebit — CHANGES_REQUESTED** [review]
Needs the checkout action for Alpine to complete.

**Comment by serebit** [comment]
I fixed Alpine in v1, so this is gonna need a rebase.

**Comment by serebit** [comment]
Ended up just taking your changes and building on top of them. You're still marked as the author for your commits. Closing.

**Comment by Conan-Kudo** [comment]
No worries, thanks! Sorry I didn't get to your feedback in time.

**Pull request closed without merging**
